CREATE DATABASE IF NOT EXISTS Pokewebapp;
USE Pokewebapp;
CREATE TABLE IF NOT EXISTS Usuario(
id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(250) NOT NULL,
contrasena VARCHAR(20) NOT NULL,
numero_tarjeta VARCHAR(18) NOT NULL,
numero_secreto VARCHAR(3) NOT NULL,
fecha_creacion TIMESTAMP
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pokemon(
id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
img_id INTEGER UNSIGNED,
especie VARCHAR(25) NOT NULL,
nombre VARCHAR(25),
peso INTEGER NOT NULL,
altura INTEGER NOT NULL,
baxp INTEGER NOT NULL
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pokedek(
id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
id_usuario INTEGER UNSIGNED,
FOREIGN KEY(id_usuario) REFERENCES Usuario(id)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Pokedek_pokemon(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
id_pokedek INTEGER UNSIGNED,
id_pokemon INTEGER UNSIGNED,
FOREIGN KEY (id_pokedek) REFERENCES Pokedek(id)
ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (id_pokemon) REFERENCES Pokemon(id)
ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE = InnoDB;